name: Deploy dalle_frontend

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Image
        run: docker build -t sblevinsdev/dalle_frontend  .


      - name: Publish Image to docker hub
        run: docker push sblevinsdev/dalle_frontend:latest
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}  
      - name: Pull image from docker hub
        run: docker pull sblevinsdev/dalle_frontend:latest
      - name: Delete old container
        run: docker rm -f dalle-frontend-container
      - name: Run Docker Container
        run: docker run -d -p 5173:80 --name dalle-frontend-container -e VITE_APP_API_URL='${{ secrets.VITE_APP_API_URL }}' sblevinsdev/dalle_frontend:latest